---
# Base rolunde olmasi gereken dizinleri iceren dosyadir.
base_ahtapot_directories:
    directory01:
        path: "/var/log/ahtapot/"
        owner: "ahtapotops"
        group: "ahtapotops"
        mode: "0755"
        state: "directory"
    directory02:
        path: "/home/ahtapotops/.ssh/"
        owner: "ahtapotops"
        group: "ahtapotops"
        mode: "0700"
        state: "directory"            
    directory03:
        path: "/home/ahtapotops/.ssh/authorized_keys"
        owner: "ahtapotops"
        group: "ahtapotops"
        mode: "0600"
        state: "touch"
#    directoryXX:
#        path: ""
#        owner: ""
#        group: ""
#        mode: ""
#        state: ""
