---
# Paket degiskenlerini iceren dosyadir.
# Yorum satiri ile gosterilen sablon doldurularak istenilen kadar paket eklenebilir.
base_packages:
    package01:
        #name: "auditd=1:2.4-1+b1" 
        name: "auditd" 
        state: "present" 
    package02:
        #name: "sysstat=11.0.1-1" 
        name: "sysstat" 
        state: "present" 
    package03:
        name: "ntp" 
        state: "present" 
    package04:
        name: "bash" 
        state: "present" 
    package05:
        name: "sudo" 
        state: "present" 
    package06:
        #name: "logrotate=3.8.7-1+b1" 
        name: "logrotate" 
        state: "present" 
    package07:
        name: "apt-transport-https" 
        state: "present"
#    packageXX:
#        name: 
#        state:  
